# Generated by Django 3.2.11 on 2022-03-10 14:50

import book.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200, unique=True)),
                ('author', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Fantasy', 'Fantasy'), ('Literary', 'Literary'), ('Mystery', 'Mystery'), ('Non-Fiction', 'Non-Fiction'), ('Science', 'Science'), ('Fiction', 'Fiction'), ('Thriller', 'Thriller')], max_length=200, null=True)),
                ('review', models.IntegerField(null=True)),
                ('rating', models.IntegerField(null=True, validators=[book.models.validate_rate])),
                ('favourites', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to='pic')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
